---
title: "DGaz"
author: "Erin Anderson"
date: "`r Sys.Date()`"
output: html_document
---


```{r 3, include=FALSE}
pupa_weight_new <- read.csv("raw_pupaweight - Sheet1.csv")
pupa_weight_new
pupa_weight_new <- na.omit(pupa_weight_new)
```

 
```{r 4, include=FALSE}
treatment1 <- pupa_weight_new$Treatment
dung <- pupa_weight_new$Dung
treatment_dung <- pupa_weight_new$X
weight <- pupa_weight_new$PWeight
```

```{r 5, include=TRUE}
library(ggplot2)
p <- ggplot(data = pupa_weight_new, aes(x = Treatment, y = PWeight, fill = Dung))  #define the variables
p <- p + geom_boxplot()  #graph them in a boxplot
p <- p + theme(axis.text.x = element_text(angle = 90))  #put x-axis names at 90deg
p <- p + ylab("Pupa Weights (g)") + xlab("Treatment") #rename y-axis title
p <- p + scale_fill_manual(values = c(Grass = "#a9dd9a", Hay = "lightyellow"))
p  #show me the graph
```
```{r 6, include=TRUE}
results_aov <- aov(pupa_weight_new$PWeight ~ pupa_weight_new$X, data= pupa_weight_new, var.equal=TRUE)
summary(results_aov)
TukeyHSD(results_aov)
```
